#!/usr/bin/env python3
"""Synchronize authored project rules and lifecycle hooks to vendor formats."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError:
    yaml = None

YAML_ERROR = yaml.YAMLError if yaml is not None else ValueError


sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parents[2]
RULE_SOURCE_DIR = ROOT / "framework" / "rules"
ENGINE_FILE = ROOT / "framework" / "engine.txt"
ENGINES_DIR = ROOT / "engines"
CLAUDE_RULE_DIR = ROOT / ".claude" / "rules"
HOOK_MANIFEST = ROOT / "hooks" / "manifest.yaml"
CLAUDE_SETTINGS = ROOT / ".claude" / "settings.json"
CODEX_HOOKS = ROOT / ".codex" / "hooks.json"
RULE_COMMENT = (
    "<!-- generated by tools/framework/sync.py from "
    "{source}; edit the source -->"
)
AGENTS_COMMENT = (
    "<!-- generated by tools/framework/sync.py from "
    "{sources}; edit the sources -->"
)
REQUIRED_HOOK_FIELDS = {
    "event",
    "script",
    "timeout",
    "claude_matcher",
    "codex_matcher",
    "vendors",
}
VALID_VENDORS = {"claude", "codex"}


def decode(path: Path) -> str:
    return path.read_bytes().decode("utf-8")


def newline_for(text: str) -> str:
    return "\r\n" if "\r\n" in text else "\n"


def load_yaml(text: str) -> Any:
    if yaml is not None:
        return yaml.safe_load(text)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        paths: list[str] = []
        lines = [line.strip() for line in text.splitlines() if line.strip()]
        if not lines or lines[0] != "paths:":
            raise ValueError("PyYAML is unavailable and the YAML is outside the supported subset")
        for line in lines[1:]:
            if not line.startswith("- "):
                raise ValueError("PyYAML is unavailable and paths frontmatter is malformed")
            value = line[2:].strip()
            paths.append(json.loads(value) if value.startswith('"') else value)
        return {"paths": paths}


def split_rule(path: Path) -> tuple[list[str], str, str]:
    text = decode(path)
    lines = text.splitlines(keepends=True)
    if not lines:
        raise ValueError(f"empty rule: {path.relative_to(ROOT)}")

    first = lines[0].strip()
    if first == "---":
        metadata_start = 1
        boundary_start = 1
    elif first == "paths:":
        metadata_start = 0
        boundary_start = 0
    else:
        raise ValueError(f"missing paths frontmatter: {path.relative_to(ROOT)}")

    boundary = next(
        (index for index in range(boundary_start, len(lines)) if lines[index].strip() == "---"),
        None,
    )
    if boundary is None or (first == "---" and boundary == 0):
        raise ValueError(f"unterminated frontmatter: {path.relative_to(ROOT)}")

    metadata_text = "".join(lines[metadata_start:boundary])
    metadata = load_yaml(metadata_text)
    paths = metadata.get("paths") if isinstance(metadata, dict) else None
    if not isinstance(paths, list) or not all(isinstance(item, str) for item in paths):
        raise ValueError(f"paths must be a string list: {path.relative_to(ROOT)}")

    return paths, "".join(lines[: boundary + 1]), "".join(lines[boundary + 1 :])


def generated_rule(path: Path, frontmatter: str, body: str) -> str:
    newline = newline_for(frontmatter + body)
    separator = "" if frontmatter.endswith(("\n", "\r")) else newline
    comment = RULE_COMMENT.format(source=path.relative_to(ROOT).as_posix())
    return f"{frontmatter}{separator}{comment}{newline}{body}"


def read_engine() -> str | None:
    """Name of the engine overlay from framework/engine.txt, or None when absent."""
    if not ENGINE_FILE.is_file():
        return None
    name = decode(ENGINE_FILE).strip()
    if not name or any(character in name for character in "/\\*?[") or name in {".", ".."}:
        raise ValueError(f"framework/engine.txt must hold a single engine name, got {name!r}")
    return name


def rule_source_dirs() -> list[Path]:
    """Generic rules first, then the engine overlay's rules when one is selected."""
    directories = [RULE_SOURCE_DIR]
    engine = read_engine()
    if engine is not None:
        overlay = ENGINES_DIR / engine / "rules"
        if not overlay.is_dir():
            raise ValueError(
                f"framework/engine.txt names '{engine}' but "
                f"{overlay.relative_to(ROOT).as_posix()} is missing"
            )
        directories.append(overlay)
    return directories


def fixed_directory(pattern: str) -> Path | None:
    normalized = pattern.replace("\\", "/")
    if not normalized.endswith("/**"):
        return None

    prefix = normalized[:-3].rstrip("/")
    # wildcards and <placeholders> are not a fixed directory: no nested AGENTS.md
    if not prefix or any(character in prefix for character in "*?[<>"):
        return None

    parts = prefix.split("/")
    if parts[0].lower() == "assets":
        parts[0] = "assets"
    if any(part in {"", ".", ".."} for part in parts):
        raise ValueError(f"unsafe rule path: {pattern}")
    return Path(*parts)


def expected_rules() -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    targeted_bodies: dict[Path, list[str]] = defaultdict(list)
    targeted_sources: dict[Path, list[str]] = defaultdict(list)
    seen_targets: dict[Path, set[str]] = defaultdict(set)

    rule_paths: list[Path] = []
    seen_names: dict[str, Path] = {}
    for source_dir in rule_source_dirs():
        for rule_path in sorted(source_dir.glob("*.md"), key=lambda item: item.name.lower()):
            if rule_path.name in seen_names:
                raise ValueError(
                    f"rule name clash: {seen_names[rule_path.name].relative_to(ROOT).as_posix()}"
                    f" and {rule_path.relative_to(ROOT).as_posix()}"
                )
            seen_names[rule_path.name] = rule_path
            rule_paths.append(rule_path)
    if not rule_paths:
        raise ValueError("no authored rules found under framework/rules or the engine overlay")

    for rule_path in rule_paths:
        patterns, frontmatter, body = split_rule(rule_path)
        generated = generated_rule(rule_path, frontmatter, body)
        outputs[CLAUDE_RULE_DIR / rule_path.name] = generated.encode("utf-8")

        for pattern in patterns:
            directory = fixed_directory(pattern)
            if directory is None or rule_path.name in seen_targets[directory]:
                continue
            seen_targets[directory].add(rule_path.name)
            targeted_bodies[directory].append(body.strip("\r\n"))
            targeted_sources[directory].append(rule_path.relative_to(ROOT).as_posix())

    for directory, bodies in sorted(targeted_bodies.items(), key=lambda item: item[0].as_posix()):
        comment = AGENTS_COMMENT.format(sources=", ".join(targeted_sources[directory]))
        content = comment + "\n\n" + "\n\n".join(bodies) + "\n"
        outputs[ROOT / directory / "AGENTS.md"] = content.encode("utf-8")

    return outputs


def load_hook_manifest() -> list[dict[str, Any]]:
    entries = load_yaml(decode(HOOK_MANIFEST))
    if not isinstance(entries, list):
        raise ValueError("hooks/manifest.yaml must contain a list")

    for index, entry in enumerate(entries, start=1):
        if not isinstance(entry, dict) or set(entry) != REQUIRED_HOOK_FIELDS:
            raise ValueError(f"hook entry {index} must contain exactly {sorted(REQUIRED_HOOK_FIELDS)}")
        if not isinstance(entry["event"], str) or not isinstance(entry["script"], str):
            raise ValueError(f"hook entry {index} needs string event and script values")
        if entry["timeout"] is not None and not isinstance(entry["timeout"], int):
            raise ValueError(f"hook entry {index} timeout must be an integer or null")
        for key in ("claude_matcher", "codex_matcher"):
            if entry[key] is not None and not isinstance(entry[key], str):
                raise ValueError(f"hook entry {index} {key} must be a string or null")
        vendors = entry["vendors"]
        if not isinstance(vendors, list) or not vendors or not set(vendors) <= VALID_VENDORS:
            raise ValueError(f"hook entry {index} has invalid vendors")

    return entries


def hook_command(script: str, vendor: str) -> str:
    if vendor == "codex":
        return script.replace("$CLAUDE_PROJECT_DIR", "$(git rev-parse --show-toplevel)")
    return script


def vendor_hooks(entries: list[dict[str, Any]], vendor: str) -> dict[str, list[dict[str, Any]]]:
    result: dict[str, list[dict[str, Any]]] = {}
    matcher_key = f"{vendor}_matcher"
    for entry in entries:
        if vendor not in entry["vendors"]:
            continue

        handler: dict[str, Any] = {
            "type": "command",
            "command": hook_command(entry["script"], vendor),
        }
        if entry["timeout"] is not None:
            handler["timeout"] = entry["timeout"]

        group: dict[str, Any] = {}
        matcher = entry[matcher_key]
        if matcher is not None:
            group["matcher"] = matcher
        group["hooks"] = [handler]
        result.setdefault(entry["event"], []).append(group)

    return result


def find_json_object_end(text: str, start: int) -> int:
    depth = 0
    in_string = False
    escaped = False
    for index in range(start, len(text)):
        character = text[index]
        if in_string:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            continue
        if character == '"':
            in_string = True
        elif character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("unterminated hooks object in .claude/settings.json")


def settings_with_hooks(settings: str, hooks: dict[str, Any]) -> str:
    match = re.search(r'(?m)^([ \t]*)"hooks"[ \t]*:[ \t]*', settings)
    if match is None:
        raise ValueError(".claude/settings.json has no top-level hooks property")

    value_start = match.end()
    if value_start >= len(settings) or settings[value_start] != "{":
        raise ValueError(".claude/settings.json hooks value is not an object")
    value_end = find_json_object_end(settings, value_start)
    newline = newline_for(settings)
    rendered = json.dumps(hooks, indent=2, ensure_ascii=False)
    rendered = rendered.replace("\n", newline + match.group(1))
    return settings[:value_start] + rendered + settings[value_end + 1 :]


def expected_outputs() -> dict[Path, bytes]:
    outputs = expected_rules()
    entries = load_hook_manifest()
    claude_hooks = vendor_hooks(entries, "claude")
    codex_hooks = {"hooks": vendor_hooks(entries, "codex")}

    settings = decode(CLAUDE_SETTINGS)
    outputs[CLAUDE_SETTINGS] = settings_with_hooks(settings, claude_hooks).encode("utf-8")
    outputs[CODEX_HOOKS] = (json.dumps(codex_hooks, indent=2, ensure_ascii=False) + "\n").encode(
        "utf-8"
    )
    return outputs


def synchronize(check: bool) -> int:
    outputs = expected_outputs()
    differences: list[Path] = []
    for path, expected in outputs.items():
        actual = path.read_bytes() if path.exists() else None
        if actual == expected:
            continue
        differences.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)

    if differences:
        action = "would update" if check else "updated"
        for path in differences:
            print(f"{action}: {path.relative_to(ROOT).as_posix()}")
    else:
        print("generated files are current")
    return 1 if check and differences else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check generated files without writing")
    arguments = parser.parse_args()
    try:
        return synchronize(arguments.check)
    except (OSError, UnicodeError, ValueError, YAML_ERROR) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
